CREATE TABLE IF NOT EXISTS STUDENT (
    ROLL_TEXT TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    AGE INTEGER
);

INSERT INTO STUDENT (ROLL_TEXT, NAME, ADDRESS, AGE) VALUES
('1', 'RAM', 'DELHI', 18),
('2', 'RAMESH', 'GURGAON', 18),
('3', 'SUJI', 'ROHTAK', 20),
('4', 'SURASH', 'DELHI', 18),
('5', 'AYANN', 'ROHTAK', 56),
('6', 'PAUL', 'PUNE', 23);

SELECT * FROM STUDENT;

SELECT * FROM STUDENT WHERE AGE = 18 AND ADDRESS = 'DELHI';

SELECT * FROM STUDENT WHERE AGE = 18 AND NAME = 'RAM';

SELECT * FROM STUDENT WHERE NAME = 'RAM' OR NAME = 'SUJI';

SELECT * FROM STUDENT WHERE NAME = 'RAM' OR AGE = 20;

SELECT * FROM STUDENT WHERE AGE = 18 AND (NAME = 'RAM' OR NAME = 'RAMESH');
